[package]
name = "erc20"
version = "0.0.0"
authors = [ "Pavlos Polianidis <info@apocentre.com>",]
edition = "2018"
publish = false

[lib]
path = "src/erc20.rs"

[dependencies.elrond-wasm]
version = "0.23.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.23.0"
